### ISSUE TITLE
Unable to run `from reemployct_data_entry import entry` or `entry.main()`

### ISSUE THREAD

**Issue by iplaywithdrums** [ariffjeff/ReEmployCT-Data-Entry#37]
**Describe the bug**
I am running into a problem at the `from reemployct_data_entry import entry` step.

I get the following error message:

```
>>> from reemployct_data_entry import entry

Job data Excel template: C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\reemployct_data_entry\workSearch_template.xlsx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\reemployct_data_entry\entry.py", line 8, in <module>
    from reemployct_data_entry import navigate_ReEmployCT, upgrade_check
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\reemployct_data_entry\navigate_ReEmployCT.py", line 6, in <module>
    from reemployct_data_entry import entry_weeklyCertification, entry_workSearch
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\reemployct_data_entry\entry_workSearch.py", line 6, in <module>
    from reemployct_data_entry.lib.job_control import PortalJobEntry
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\reemployct_data_entry\lib\job_control.py", line 4, in <module>
    import pandas as pd
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\compat\__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\util\__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

and when I try to `entry.main()`, I get:

```
>>> entry.main()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'entry' is not defined
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser [e.g. Firefox, Chrome]
 - Python Version 3.12.6

**Comment by ariffjeff** [comment]
Try running with python 3.10.10 and let me know if it works.

**Comment by iplaywithdrums** [comment]
Nope, still happening.

```
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from reemployct_data_entry import entry

Job data Excel template: C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\reemployct_data_entry\workSearch_template.xlsx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\reemployct_data_entry\entry.py", line 8, in <module>
    from reemployct_data_entry import navigate_ReEmployCT, upgrade_check
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\reemployct_data_entry\navigate_ReEmployCT.py", line 6, in <module>
    from reemployct_data_entry import entry_weeklyCertification, entry_workSearch
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\reemployct_data_entry\entry_workSearch.py", line 6, in <module>
    from reemployct_data_entry.lib.job_control import PortalJobEntry
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\reemployct_data_entry\lib\job_control.py", line 4, in <module>
    import pandas as pd
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\compat\__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "C:\Users\Macy\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by ariffjeff** [comment]
Wack. Ok I'll try to fix this.

**Comment by ariffjeff** [comment]
I'm able to reproduce the error. I'll get on fixing it as soon as I can in the next several hours, if not tomorrow.

**Comment by ariffjeff** [comment]
I've found that updating the pandas dependency fixes the crash. I've changed it in the requirements so if you install the latest release then the dependency should be updated. Try running the program again after that.

**Comment by iplaywithdrums** [comment]
That works now. Does it still only work with `3.10.10`?

**Comment by ariffjeff** [comment]
I tested on 3.10.10 and 3.12.1 and both worked. You should be able to use any python version above 3.10.10 reliably with no problems... theoretically.
